# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_baemin_waiting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_baemin_waiting
  pod 'SwiftLint'
  target 'ios_baemin_waitingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_baemin_waitingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
