# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'SwiftLint'

target 'ios_baemin_waiting' do
  use_frameworks!

  # Pods for ios_baemin_waiting

  target 'BaeminWaitingUnitTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
